[book]
authors = ["joshxyzhimself"]
language = "en"
multilingual = false
src = "src"
title = "Venture Index"
description = "Indexing the Philippine startup ecosystem."

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/ventureindexco/web"
edit-url-template = "https://github.com/ventureindexco/web/edit/main/{path}"
cname = "ventureindex.co"
